name: Build Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/dizyz/python-selenium:latest
            ghcr.io/dizys/python-selenium:${{ github.sha }}
